### ISSUE TITLE
Doesn't work with `import` instead of `require`

### ISSUE THREAD

**Issue by nikolasburk** [relayjs/relay-codemod#1]
Running `jscodeshift -t relay-codemod/transforms/migrate-to-modern-1.0.js <file>` only works if `file` uses `require` to import Relay:

```
var Relay = require('react-relay/classic');
```

It doesn't work with `import`:

```
import Relay from 'react-relay/classic'
```

**Comment by sibelius** [comment]
maybe this could help

https://github.com/sibelius/codemod-RN24-to-RN25/pull/9/files

**Comment by alangenfeld** [comment]
Ya migrate-to-modern is currently just a set of very crude regex. Though I did try to test that the import case worked https://github.com/relayjs/relay-codemod/blob/master/test/modern/SimpleImport.js so not sure why it didn't work for your case. 

Happy to accept any PRs for this.

**Comment by schickling** [comment]
I think it's due to the missing `;` in @nikolasburk snippet. This should be a very simple fix though @alangenfeld.

**Comment by alangenfeld** [comment]
ah good catch, pushed a fix to not assume semicolons
